services:
  user-service:
    build: .
    command: uvicorn services.user.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8001:8000"

  payment-service:
    build: .
    command: uvicorn services.payment.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8003:8000"

  order-service:
    build: .
    command: uvicorn services.order.main:app --host 0.0.0.0 --port 8000
    environment:
      USER_SERVICE_URL: http://user-service:8000
      PAYMENT_SERVICE_URL: http://payment-service:8000
    ports:
      - "8002:8000"
    depends_on:
      - user-service
      - payment-service
